import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { Activity, Bell, ChevronRight, CircleDollarSign, LayoutDashboard, LogOut, Menu, Package, Plus, Radio, RefreshCw, Router as RouterIcon, Search, ShieldCheck, Users, Wifi, X } from "lucide-react";
import { listRouters, provisionCustomer } from "@/lib/mikrotik.functions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { supabase } from "@/integrations/supabase/client";
import type { Tables } from "@/integrations/supabase/types";

export type Customer = Tables<"customers"> & { plans: Pick<Tables<"plans">, "name"> | null };
export type Plan = Tables<"plans">;

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [
    { title: "Painel | Nexora ISP" },
    { name: "description", content: "Visão operacional de clientes e planos do provedor." },
    { property: "og:title", content: "Painel | Nexora ISP" },
    { property: "og:description", content: "Visão operacional de clientes e planos do provedor." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Dashboard,
});

function Dashboard() {
  const navigate = useNavigate();
  const { user } = Route.useRouteContext();
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [panel, setPanel] = useState<"customer" | "plan" | null>(null);
  const [editing, setEditing] = useState<Customer | null>(null);
  const [query, setQuery] = useState("");
  const [mobileNav, setMobileNav] = useState(false);
  const [message, setMessage] = useState("");
  const listRoutersFn = useServerFn(listRouters);
  const provisionFn = useServerFn(provisionCustomer);
  const [routers, setRouters] = useState<{ id: string; name: string }[]>([]);
  const [syncing, setSyncing] = useState<string | null>(null);
  async function loadData() {
    const [customerResult, planResult] = await Promise.all([supabase.from("customers").select("*, plans(name)").order("created_at", { ascending: false }), supabase.from("plans").select("*").order("created_at", { ascending: false })]);
    setCustomers((customerResult.data ?? []) as Customer[]); setPlans(planResult.data ?? []);
    try { setRouters(await listRoutersFn()); } catch { setRouters([]); }
  }
  useEffect(() => { void loadData(); }, []);
  const filtered = useMemo(() => customers.filter(c => `${c.full_name} ${c.document} ${c.pppoe_username ?? ""} ${String(c.ipoe_ip ?? "")}`.toLowerCase().includes(query.toLowerCase())), [customers, query]);
  async function savePlan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const { error } = await supabase.from("plans").insert({ name: String(f.get("name")), download_mbps: Number(f.get("download")), upload_mbps: Number(f.get("upload")), monthly_price: Number(f.get("price")), technology: String(f.get("technology")) as "pppoe" | "ipoe" }); if (error) setMessage(error.message); else { setPanel(null); setMessage(""); await loadData(); } }
  async function saveCustomer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const technology = String(f.get("technology")) as "pppoe" | "ipoe"; if (technology === "ipoe") { const mac = String(f.get("mac") ?? "").trim(); if (!/^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$/.test(mac)) { setMessage("Endereço MAC inválido. Use o formato AA:BB:CC:DD:EE:FF."); return; } const ip = String(f.get("connection") ?? "").trim(); if (!/^(\d{1,3}\.){3}\d{1,3}$/.test(ip)) { setMessage("Endereço IP inválido. Use o formato 100.64.0.10."); return; } } const payload = { full_name: String(f.get("name")), document: String(f.get("document")), phone: String(f.get("phone")), email: String(f.get("email") ?? "") || null, technology, plan_id: String(f.get("plan") ?? "") || null, router_id: String(f.get("router") ?? "") || null, pppoe_username: technology === "pppoe" ? String(f.get("connection")) : null, pppoe_password: technology === "pppoe" ? String(f.get("secret")) || null : null, ipoe_ip: technology === "ipoe" ? String(f.get("connection")) : null, mac_address: technology === "ipoe" ? String(f.get("mac")).trim().toUpperCase().replace(/-/g, ":") : null, notes: String(f.get("notes") ?? "") || null }; const { error } = editing ? await supabase.from("customers").update(payload).eq("id", editing.id) : await supabase.from("customers").insert({ ...payload, created_by: user.id }); if (error) setMessage(error.message); else { setPanel(null); setEditing(null); setMessage(""); await loadData(); } }
  async function provision(id: string) { setSyncing(id); try { const r = await provisionFn({ data: { id } }); if (!r.ok) alert(r.error); } catch (e) { alert((e as Error).message); } finally { setSyncing(null); await loadData(); } }
  async function setStatus(id: string, status: Customer["status"]) { const { error } = await supabase.from("customers").update({ status }).eq("id", id); if (error) return alert(error.message); await provision(id); }
  async function signOut() { await supabase.auth.signOut(); navigate({ to: "/auth", replace: true }); }
  const active = customers.filter(c => c.status === "active").length;
  const suspended = customers.filter(c => c.status === "suspended").length;
  const monthly = customers.filter(c => c.status === "active").reduce((sum, c) => sum + Number(plans.find(p => p.id === c.plan_id)?.monthly_price ?? 0), 0);
  const nav = <><div className="flex h-16 items-center gap-3 px-5 text-lg font-extrabold"><span className="flex h-9 w-9 items-center justify-center rounded-md bg-sidebar-primary text-sidebar-primary-foreground"><Radio /></span>NEXORA <span className="text-sidebar-primary">ISP</span></div><nav className="mt-5 space-y-1 px-3"><Nav icon={<LayoutDashboard />} label="Visão geral" active /><Link to="/clientes"><Nav icon={<Users />} label="Clientes" /></Link><Nav icon={<Package />} label="Planos" /><Link to="/mikrotik"><Nav icon={<RouterIcon />} label="MikroTik" /></Link><Link to="/usuarios"><Nav icon={<ShieldCheck />} label="Usuários" /></Link><Nav icon={<Wifi />} label="Conexões" /><Nav icon={<CircleDollarSign />} label="Financeiro" /></nav><div className="mt-auto border-t border-sidebar-border p-3"><Button variant="ghost" className="w-full justify-start text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground" onClick={signOut}><LogOut />Sair</Button></div></>;
  return <div className="min-h-screen bg-background text-foreground lg:grid lg:grid-cols-[240px_1fr]">
    <aside className="hidden min-h-screen flex-col bg-sidebar text-sidebar-foreground lg:flex">{nav}</aside>
    {mobileNav && <div className="fixed inset-0 z-50 flex bg-foreground/30 lg:hidden"><aside className="flex w-64 flex-col bg-sidebar text-sidebar-foreground">{nav}</aside><Button variant="ghost" size="icon" aria-label="Fechar menu" onClick={() => setMobileNav(false)}><X /></Button></div>}
    <main className="min-w-0"><header className="flex h-16 items-center gap-3 border-b bg-card px-4 md:px-7"><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Abrir menu" onClick={() => setMobileNav(true)}><Menu /></Button><div><p className="font-bold">Visão geral</p><p className="hidden text-xs text-muted-foreground sm:block">Acompanhe sua operação em tempo real</p></div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Notificações"><Bell /></Button><div className="hidden h-9 w-9 items-center justify-center rounded-full bg-primary font-bold text-primary-foreground sm:flex">{user.email?.slice(0,2).toUpperCase()}</div></div></header>
      <div className="p-4 md:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-muted-foreground">Operação em tempo real</p><h1 className="mt-1 text-2xl font-extrabold md:text-3xl">Resumo da operação</h1></div><div className="flex gap-2"><Button variant="outline" onClick={() => setPanel("plan")}><Package />Novo plano</Button><Button onClick={() => { setEditing(null); setPanel("customer"); }}><Plus />Novo cliente</Button></div></div>
        <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Clientes ativos" value={active} detail={`${customers.length} cadastrados`} icon={<Users />} tone="primary" /><Metric label="Conexões online" value={active} detail="Acessos monitorados" icon={<Activity />} tone="green" /><Metric label="Suspensos" value={suspended} detail="Aguardando regularização" icon={<Wifi />} tone="amber" /><Metric label="Receita mensal" value={monthly.toLocaleString("pt-BR", { style: "currency", currency: "BRL" })} detail="Base ativa atual" icon={<CircleDollarSign />} tone="blue" /></section>
        <section className="mt-7 border bg-card"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">Clientes recentes</h2><p className="text-xs text-muted-foreground">Cadastros PPPoE e IPoE</p></div><div className="relative sm:ml-auto"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9 sm:w-72" placeholder="Buscar cliente ou acesso" value={query} onChange={e => setQuery(e.target.value)} /></div></div><Table><TableHeader><TableRow><TableHead>Cliente</TableHead><TableHead>Tecnologia</TableHead><TableHead>Plano</TableHead><TableHead>Acesso</TableHead><TableHead>Status</TableHead><TableHead className="w-12" /></TableRow></TableHeader><TableBody>{filtered.map(c => <TableRow key={c.id}><TableCell><p className="font-semibold">{c.full_name}</p><p className="text-xs text-muted-foreground">{c.document}</p></TableCell><TableCell><Badge variant="outline">{c.technology.toUpperCase()}</Badge></TableCell><TableCell>{c.plans?.name ?? "Sem plano"}</TableCell><TableCell className="font-mono text-xs">{c.pppoe_username ?? String(c.ipoe_ip ?? "—")}</TableCell><TableCell><Status status={c.status} /><p className={`mt-1 text-xs ${c.sync_status === "error" ? "text-destructive" : "text-muted-foreground"}`} title={c.sync_error ?? ""}>{c.sync_status === "synced" ? "No roteador" : c.sync_status === "error" ? "Falha na sincronização" : "Não provisionado"}</p></TableCell><TableCell className="whitespace-nowrap"><Button size="sm" variant="outline" onClick={() => { setEditing(c); setPanel("customer"); }}>Editar</Button><Button size="sm" variant="ghost" disabled={syncing === c.id || !c.router_id} title={c.router_id ? "Provisionar no MikroTik" : "Sem roteador vinculado"} onClick={() => provision(c.id)}><RefreshCw className={syncing === c.id ? "animate-spin" : ""} />Provisionar</Button>{c.status === "suspended" ? <Button size="sm" variant="outline" onClick={() => setStatus(c.id, "active")}>Reativar</Button> : <Button size="sm" variant="outline" onClick={() => setStatus(c.id, "suspended")}>Suspender</Button>}</TableCell></TableRow>)}{!filtered.length && <TableRow><TableCell colSpan={6} className="h-32 text-center text-muted-foreground">Nenhum cliente cadastrado.</TableCell></TableRow>}</TableBody></Table></section>
      </div></main>
    {panel && <div className="fixed inset-0 z-50 flex justify-end bg-foreground/30"><div className="h-full w-full max-w-lg overflow-y-auto bg-card p-6 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-primary">{editing ? "EDITAR CADASTRO" : "NOVO CADASTRO"}</p><h2 className="text-2xl font-extrabold">{panel === "customer" ? "Cliente" : "Plano"}</h2></div><Button variant="ghost" size="icon" aria-label="Fechar" onClick={() => { setPanel(null); setEditing(null); }}><X /></Button></div>{panel === "customer" ? <CustomerForm key={editing?.id ?? "new"} plans={plans} routers={routers} initial={editing} onSubmit={saveCustomer} /> : <PlanForm onSubmit={savePlan} />}{message && <p className="mt-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{message}</p>}</div></div>}
  </div>;
}
function Nav({ icon, label, active = false }: { icon: ReactNode; label: string; active?: boolean }) { return <div className={`flex h-10 items-center gap-3 rounded-md px-3 text-sm font-medium ${active ? "bg-sidebar-accent text-sidebar-primary" : "text-sidebar-foreground/65"}`}>{icon}<span>{label}</span>{active && <ChevronRight className="ml-auto h-4 w-4" />}</div>; }
function Metric({ label, value, detail, icon, tone }: { label: string; value: string | number; detail: string; icon: ReactNode; tone: string }) { return <article className="border bg-card p-5"><div className="flex items-center justify-between"><p className="text-sm font-medium text-muted-foreground">{label}</p><span className={`metric-icon metric-${tone}`}>{icon}</span></div><p className="mt-5 text-3xl font-extrabold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></article>; }
export function Status({ status }: { status: Customer["status"] }) { const text = { active: "Ativo", suspended: "Suspenso", pending: "Pendente", cancelled: "Cancelado" }[status]; return <Badge variant={status === "active" ? "default" : status === "suspended" ? "destructive" : "secondary"}>{text}</Badge>; }
export function CustomerForm({ plans, routers, initial, onSubmit }: { plans: Plan[]; routers: { id: string; name: string }[]; initial?: Customer | null; onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { const [tech, setTech] = useState(initial?.technology ?? "pppoe"); return <form onSubmit={onSubmit} className="mt-8 space-y-5"><Field label="Nome completo"><Input name="name" required defaultValue={initial?.full_name ?? ""} /></Field><div className="grid grid-cols-2 gap-3"><Field label="CPF/CNPJ"><Input name="document" required defaultValue={initial?.document ?? ""} /></Field><Field label="Telefone"><Input name="phone" required defaultValue={initial?.phone ?? ""} /></Field></div><Field label="E-mail"><Input name="email" type="email" defaultValue={initial?.email ?? ""} /></Field><Field label="Tecnologia"><Select name="technology" value={tech} onValueChange={v => setTech(v as "pppoe" | "ipoe")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pppoe">PPPoE</SelectItem><SelectItem value="ipoe">IPoE</SelectItem></SelectContent></Select></Field><Field label="Plano"><Select name="plan" {...(initial?.plan_id ? { defaultValue: initial.plan_id } : {})}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{plans.filter(p => p.status === "active").map(p => <SelectItem key={p.id} value={p.id}>{p.name} · {p.download_mbps} Mbps</SelectItem>)}</SelectContent></Select></Field><Field label="Roteador MikroTik"><Select name="router" {...(initial?.router_id ? { defaultValue: initial.router_id } : {})}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{routers.map(r => <SelectItem key={r.id} value={r.id}>{r.name}</SelectItem>)}</SelectContent></Select></Field><Field label={tech === "pppoe" ? "Usuário PPPoE" : "Endereço IP"}><Input name="connection" required defaultValue={tech === "pppoe" ? initial?.pppoe_username ?? "" : String(initial?.ipoe_ip ?? "")} placeholder={tech === "pppoe" ? "cliente@provedor" : "100.64.0.10"} /></Field>{tech === "pppoe" && <Field label="Senha PPPoE"><Input name="secret" type="password" required={!initial} defaultValue={initial?.pppoe_password ?? ""} /></Field>}{tech === "ipoe" && <Field label="Endereço MAC"><Input name="mac" required defaultValue={initial?.mac_address ? String(initial.mac_address) : ""} placeholder="AA:BB:CC:DD:EE:FF" pattern="([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}" title="Formato: AA:BB:CC:DD:EE:FF" /></Field>}<Field label="Observações"><Input name="notes" defaultValue={initial?.notes ?? ""} /></Field><Button className="h-11 w-full" type="submit">{initial ? "Salvar alterações" : "Salvar cliente"}</Button></form>; }
function PlanForm({ onSubmit }: { onSubmit: (e: FormEvent<HTMLFormElement>) => void }) { return <form onSubmit={onSubmit} className="mt-8 space-y-5"><Field label="Nome do plano"><Input name="name" required placeholder="Fibra 500 Mega" /></Field><div className="grid grid-cols-2 gap-3"><Field label="Download (Mbps)"><Input name="download" type="number" min="1" required /></Field><Field label="Upload (Mbps)"><Input name="upload" type="number" min="1" required /></Field></div><Field label="Mensalidade"><Input name="price" type="number" min="0" step="0.01" required /></Field><Field label="Tecnologia"><Select name="technology" defaultValue="pppoe"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pppoe">PPPoE</SelectItem><SelectItem value="ipoe">IPoE</SelectItem></SelectContent></Select></Field><Button className="h-11 w-full" type="submit">Salvar plano</Button></form>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }