/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMikrotikRouteImport } from './routes/_authenticated/mikrotik'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPrecosRouteImport } from './routes/_authenticated/precos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as ApiPublicHooksSyncMikrotikRouteImport } from './routes/api/public/hooks/sync-mikrotik'
import { Route as ApiPublicRadiusActionRouteImport } from './routes/api/public/radius.$action'
import { Route as ApiPublicWebhooksAsaasRouteImport } from './routes/api/public/webhooks/asaas'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMikrotikRoute = AuthenticatedMikrotikRouteImport.update({
  id: '/mikrotik',
  path: '/mikrotik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecosRoute = AuthenticatedPrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSyncMikrotikRoute =
  ApiPublicHooksSyncMikrotikRouteImport.update({
    id: '/api/public/hooks/sync-mikrotik',
    path: '/api/public/hooks/sync-mikrotik',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRadiusActionRoute = ApiPublicRadiusActionRouteImport.update({
  id: '/api/public/radius/$action',
  path: '/api/public/radius/$action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAsaasRoute = ApiPublicWebhooksAsaasRouteImport.update({
  id: '/api/public/webhooks/asaas',
  path: '/api/public/webhooks/asaas',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/mikrotik': typeof AuthenticatedMikrotikRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/hooks/sync-mikrotik': typeof ApiPublicHooksSyncMikrotikRoute
  '/api/public/radius/$action': typeof ApiPublicRadiusActionRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/mikrotik': typeof AuthenticatedMikrotikRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/precos': typeof AuthenticatedPrecosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/hooks/sync-mikrotik': typeof ApiPublicHooksSyncMikrotikRoute
  '/api/public/radius/$action': typeof ApiPublicRadiusActionRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/mikrotik': typeof AuthenticatedMikrotikRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/precos': typeof AuthenticatedPrecosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/hooks/sync-mikrotik': typeof ApiPublicHooksSyncMikrotikRoute
  '/api/public/radius/$action': typeof ApiPublicRadiusActionRoute
  '/api/public/webhooks/asaas': typeof ApiPublicWebhooksAsaasRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/mikrotik'
    | '/planos'
    | '/precos'
    | '/usuarios'
    | '/api/public/hooks/sync-mikrotik'
    | '/api/public/radius/$action'
    | '/api/public/webhooks/asaas'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/equipe'
    | '/financeiro'
    | '/mikrotik'
    | '/planos'
    | '/precos'
    | '/usuarios'
    | '/api/public/hooks/sync-mikrotik'
    | '/api/public/radius/$action'
    | '/api/public/webhooks/asaas'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/mikrotik'
    | '/_authenticated/planos'
    | '/_authenticated/precos'
    | '/_authenticated/usuarios'
    | '/api/public/hooks/sync-mikrotik'
    | '/api/public/radius/$action'
    | '/api/public/webhooks/asaas'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksSyncMikrotikRoute: typeof ApiPublicHooksSyncMikrotikRoute
  ApiPublicRadiusActionRoute: typeof ApiPublicRadiusActionRoute
  ApiPublicWebhooksAsaasRoute: typeof ApiPublicWebhooksAsaasRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mikrotik': {
      id: '/_authenticated/mikrotik'
      path: '/mikrotik'
      fullPath: '/mikrotik'
      preLoaderRoute: typeof AuthenticatedMikrotikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precos': {
      id: '/_authenticated/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof AuthenticatedPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/sync-mikrotik': {
      id: '/api/public/hooks/sync-mikrotik'
      path: '/api/public/hooks/sync-mikrotik'
      fullPath: '/api/public/hooks/sync-mikrotik'
      preLoaderRoute: typeof ApiPublicHooksSyncMikrotikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radius/$action': {
      id: '/api/public/radius/$action'
      path: '/api/public/radius/$action'
      fullPath: '/api/public/radius/$action'
      preLoaderRoute: typeof ApiPublicRadiusActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/asaas': {
      id: '/api/public/webhooks/asaas'
      path: '/api/public/webhooks/asaas'
      fullPath: '/api/public/webhooks/asaas'
      preLoaderRoute: typeof ApiPublicWebhooksAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMikrotikRoute: typeof AuthenticatedMikrotikRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPrecosRoute: typeof AuthenticatedPrecosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMikrotikRoute: AuthenticatedMikrotikRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPrecosRoute: AuthenticatedPrecosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksSyncMikrotikRoute: ApiPublicHooksSyncMikrotikRoute,
  ApiPublicRadiusActionRoute: ApiPublicRadiusActionRoute,
  ApiPublicWebhooksAsaasRoute: ApiPublicWebhooksAsaasRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
